version: '3.8'

services:
  chaisite:
    build:
      context: .
    image: chai-img:latest
    container_name: chai-cont
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
 